# Generated by Django 4.2.30 on 2026-09-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_repair_customer_name_repair_deposit_sale_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop (كاشير ديسكتوب)'), ('mobile', 'Mobile (تطبيق هاتف)'), ('tablet', 'Tablet (تابلت)')], default='desktop', max_length=20),
        ),
        migrations.AddField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='license',
            name='max_devices',
            field=models.PositiveIntegerField(default=3, help_text='الحد الأقصى للأجهزة المصرح بها (ديسكتوب وموبايل)'),
        ),
        migrations.AddField(
            model_name='license',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='license',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
    ]
