# Generated by Django 4.2.30 on 2026-09-25 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_device_device_type_device_is_active_device_last_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='end_date',
            field=models.DateField(blank=True, help_text='اتركه فارغاً ليتم حسابه تلقائياً (سنة للمدفوع، 20 يوماً للتجريبي)', null=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_key',
            field=models.CharField(blank=True, help_text='اتركه فارغاً ليتم توليد كود ترخيص تلقائي', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='license',
            name='type',
            field=models.CharField(choices=[('trial', 'Trial'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
    ]
