; Script generated by Mobile-Store Team for Commercial Distribution
#define MyAppName "Mobile-Store Management System"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "MobileStore Inc."
#define MyAppURL "http://34.175.186.221"
#define MyAppExeName "MobileStore.exe"

[Setup]
AppId={{5D9E2E8F-4B1C-4E28-8973-2B0387B19D20}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\MobileStore
DisableProgramGroupPage=yes
LicenseFile=
SetupIconFile=d:\Projects\Mobile-Store\desktop\app_icon.ico
OutputDir=d:\Projects\Mobile-Store\dist_installers
OutputBaseFilename=MobileStore-Setup
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequired=lowest

[Languages]
Name: "arabic"; MessagesFile: "compiler:Languages\Arabic.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: "d:\Projects\Mobile-Store\desktop\dist\MobileStore\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
